<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aporte extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Aporte_model');
        $this->load->model('Estado_model');
        $this->load->model('Tipo_aporte_model');
        $this->load->model('Me_model');
        $this->load->model('Gestion_model');
    } 

    /*
     * Listing of aporte
     */
    function index()
    {
        $data['aporte'] = $this->Aporte_model->get_all_aporte();
        
        $data['_view'] = 'aporte/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new aporte
     */
    function add()
    {   
        $created_date = date("Y-m-d H:i:s");
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'motivo_ap' => $this->input->post('motivo_ap'),
				'detalle_ap' => $this->input->post('detalle_ap'),
				'monto_ap' => $this->input->post('monto_ap'),
				'fechahora_ap' => $created_date,
				'mes_ap' => $this->input->post('mes_ap'),
				'gestion_ap' => $this->input->post('gestion_ap'),
				'tipo_ap' => $this->input->post('tipo_ap'),
				'estado_ap' => 'ACTIVO',
				'id_usu' => 1,
				'exento_ap' => $this->input->post('exento_ap'),
				'ice_ap' => $this->input->post('ice_ap'),
            );
            
            $aporte_id = $this->Aporte_model->add_aporte($params);
            redirect('aporte/index');
        }
        else
        {        
            $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
            $data['all_estado'] = $this->Estado_model->get_all_estados();
            $data['all_mes'] = $this->Me_model->get_all_mes();
            $data['all_tipo'] = $this->Tipo_aporte_model->get_all_tipo_aporte();
            $data['_view'] = 'aporte/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a aporte
     */
    function edit($id_ap)
    {   
        // check if the aporte exists before trying to edit it
        $data['aporte'] = $this->Aporte_model->get_aporte($id_ap);
        
        if(isset($data['aporte']['id_ap']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'motivo_ap' => $this->input->post('motivo_ap'),
					'detalle_ap' => $this->input->post('detalle_ap'),
					'monto_ap' => $this->input->post('monto_ap'),
					'fechahora_ap' => $this->input->post('fechahora_ap'),
					'mes_ap' => $this->input->post('mes_ap'),
					'gestion_ap' => $this->input->post('gestion_ap'),
					'tipo_ap' => $this->input->post('tipo_ap'),
					'estado_ap' => $this->input->post('estado_ap'),
					'id_usu' => 1,
					'exento_ap' => $this->input->post('exento_ap'),
					'ice_ap' => $this->input->post('ice_ap'),
                );

                $this->Aporte_model->update_aporte($id_ap,$params);            
                redirect('aporte/index');
            }
            else
            {
                $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
                $data['all_estado'] = $this->Estado_model->get_all_estados();
                $data['all_mes'] = $this->Me_model->get_all_mes();
                $data['all_tipo'] = $this->Tipo_aporte_model->get_all_tipo_aporte();
                $data['_view'] = 'aporte/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The aporte you are trying to edit does not exist.');
    } 

    /*
     * Deleting aporte
     */
    function remove($id_ap)
    {
        $aporte = $this->Aporte_model->get_aporte($id_ap);

        // check if the aporte exists before trying to delete it
        if(isset($aporte['id_ap']))
        {
            $this->Aporte_model->delete_aporte($id_ap);
            redirect('aporte/index');
        }
        else
            show_error('The aporte you are trying to delete does not exist.');
    }
    
}
