<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Asociado_model');
    } 

    /*
     * Listing of asociado
     */
    function index()
    {
        $data['asociado'] = $this->Asociado_model->get_all_asociado();
        
        $data['_view'] = 'asociado/index';
        $this->load->view('layouts/main',$data);
    }

    function dashboard($asociado_id)
    {
        $data['asociado'] = $this->Asociado_model->get_asociado($asociado_id);
        $data['pendientes'] = $this->Asociado_model->get_pendientes($asociado_id);
        $data['canceladas'] = $this->Asociado_model->get_canceladas($asociado_id);
        $data['_view'] = 'asociado/dashboard';
        $this->load->view('layouts/main',$data);
    }
    function ultimas_lecturas()
    {
        $asociado_id = $this->input->post('asociado_id');
        $ultimas = "SELECT l.*, a.nombres_asoc, a.apellidos_asoc, a.tipo_asoc, a.categoria_asoc  from lectura l, asociado a where a.id_asoc=l.id_asoc and l.id_asoc=".$asociado_id." order by l.fecha_lec DESC limit 5";
        $result= $this->db->query($ultimas)->result_array();
        //foreach($result as $res){
        //$mes=intval(date("m",strtotime($res['fecha_lec']) ) );
        
        //$suma=$res['consumo_lec'];
        
        //$registros[$mes]+=$suma;    
        //}
        echo json_encode($result);
         return true;
        //$data=array("registrosdia" =>$registros,);
        //echo   json_encode($data);
    }

    /*
     * Adding a new asociado
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_emp' => $this->input->post('id_emp'),
				'estado' => $this->input->post('estado'),
				'tipo_asoc' => $this->input->post('tipo_asoc'),
				'ciudad' => $this->input->post('ciudad'),
				'nombres_asoc' => $this->input->post('nombres_asoc'),
				'apellidos_asoc' => $this->input->post('apellidos_asoc'),
				'ci_asoc' => $this->input->post('ci_asoc'),
				'direccion_asoc' => $this->input->post('direccion_asoc'),
				'fechanac_asoc' => $this->input->post('fechanac_asoc'),
				'telefono_asoc' => $this->input->post('telefono_asoc'),
				'codigo_asoc' => $this->input->post('codigo_asoc'),
				'nit_asoc' => $this->input->post('nit_asoc'),
				'razon_asoc' => $this->input->post('razon_asoc'),
				'foto_asoc' => $this->input->post('foto_asoc'),
				'fechahora_asoc' => $this->input->post('fechahora_asoc'),
				'zona_asoc' => $this->input->post('zona_asoc'),
				'medidor_asoc' => $this->input->post('medidor_asoc'),
				'servicios_asoc' => $this->input->post('servicios_asoc'),
				'categoria_asoc' => $this->input->post('categoria_asoc'),
				'orden_asoc' => $this->input->post('orden_asoc'),
            );
            
            $asociado_id = $this->Asociado_model->add_asociado($params);
            redirect('asociado/index');
        }
        else
        {            
            $data['_view'] = 'asociado/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a asociado
     */
    function edit($id_asoc)
    {   
        // check if the asociado exists before trying to edit it
        $data['asociado'] = $this->Asociado_model->get_asociado($id_asoc);
        
        if(isset($data['asociado']['id_asoc']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_emp' => $this->input->post('id_emp'),
					'estado' => $this->input->post('estado'),
					'tipo_asoc' => $this->input->post('tipo_asoc'),
					'ciudad' => $this->input->post('ciudad'),
					'nombres_asoc' => $this->input->post('nombres_asoc'),
					'apellidos_asoc' => $this->input->post('apellidos_asoc'),
					'ci_asoc' => $this->input->post('ci_asoc'),
					'direccion_asoc' => $this->input->post('direccion_asoc'),
					'fechanac_asoc' => $this->input->post('fechanac_asoc'),
					'telefono_asoc' => $this->input->post('telefono_asoc'),
					'codigo_asoc' => $this->input->post('codigo_asoc'),
					'nit_asoc' => $this->input->post('nit_asoc'),
					'razon_asoc' => $this->input->post('razon_asoc'),
					'foto_asoc' => $this->input->post('foto_asoc'),
					'fechahora_asoc' => $this->input->post('fechahora_asoc'),
					'zona_asoc' => $this->input->post('zona_asoc'),
					'medidor_asoc' => $this->input->post('medidor_asoc'),
					'servicios_asoc' => $this->input->post('servicios_asoc'),
					'categoria_asoc' => $this->input->post('categoria_asoc'),
					'orden_asoc' => $this->input->post('orden_asoc'),
                );

                $this->Asociado_model->update_asociado($id_asoc,$params);            
                redirect('asociado/index');
            }
            else
            {
                $data['_view'] = 'asociado/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The asociado you are trying to edit does not exist.');
    } 

    /*
     * Deleting asociado
     */
    function remove($id_asoc)
    {
        $asociado = $this->Asociado_model->get_asociado($id_asoc);

        // check if the asociado exists before trying to delete it
        if(isset($asociado['id_asoc']))
        {
            $this->Asociado_model->delete_asociado($id_asoc);
            redirect('asociado/index');
        }
        else
            show_error('The asociado you are trying to delete does not exist.');
    }
    
}
