<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imagen_asociado extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Imagen_asociado_model');
        /*if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }*/
    }
    /* *****Funcion que verifica el acceso al sistema**** */
   /* private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            return true;
            //$data['_view'] = 'login/mensajeacceso';
            //$this->load->view('layouts/main',$data);
        }
    }*/
    function catalogoasoc($asociado_id)
    {
       // if($this->acceso(109)){
          /*  $data['page_title'] = "Imagenen Producto";
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('imagen_producto/index?');
        $config['total_rows'] = $this->Imagen_producto_model->get_all_imagen_mi_producto_count($producto_id);
        $this->pagination->initialize($config);
        */
        $this->load->model('Asociado_model');
	$asociado = $this->Asociado_model->get_asociado($asociado_id);
        $data['id_asoc'] = $asociado_id;
        $data['asociado'] = $asociado['nombres_asoc']." ".$asociado['apellidos_asoc'];
        $data['all_imagen_asociado'] = $this->Imagen_asociado_model->get_all_imagen_mi_asociado($asociado_id);
        
        $data['_view'] = 'imagen_asociado/catalogoasoc';
        $this->load->view('layouts/main',$data);
     //   }
    }
    
    function addimg_det($detalleserv_id)
    {
        //if($this->acceso(69)){
            //$this->load->library('form_validation');
            $this->load->model('Parametro_model');
            $parametro = $this->Parametro_model->get_parametro(1);
            
            $tipousuario_id = $this->session_data['tipousuario_id'];
            /* *********************INICIO imagen***************************** */
            $foto="";
            if (!empty($_FILES['galeria_imagen']['name'])){
		
                        $this->load->library('image_lib');
                        $config['upload_path'] = './resources/images/asociado/';
                        $img_full_path = $config['upload_path'];

                        $config['allowed_types'] = 'gif|jpeg|jpg|png';
                        $config['image_library'] = 'gd2';
                        $config['max_size'] = 0;
                        /*$config['max_width'] = 9900;
                        $config['max_height'] = 9900;*/
                        
                        $new_name = time(); //str_replace(" ", "_", $this->input->post('proveedor_nombre'));
                        $config['file_name'] = $new_name; //.$extencion;
                        $config['file_ext_tolower'] = TRUE;

                        $this->load->library('upload', $config);
                        $this->upload->do_upload('galeria_imagen');
                        //si´parametro es 0 ---> imagen comprimido
                        if($parametro['parametro_imagenreal'] == 0){
                        $img_data = $this->upload->data();
                        $extension = $img_data['file_ext'];
                        /* ********************INICIO para resize***************************** */
                        if ($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif")
                        {
                            $conf['image_library'] = 'gd2';
                            $conf['source_image'] = $img_data['full_path'];
                            $conf['new_image'] = './resources/images/asociado/';
                            $conf['maintain_ratio'] = TRUE;
                            $conf['create_thumb'] = FALSE;
                            $conf['width'] = 800;
                            $conf['height'] = 600;
                            $this->image_lib->clear();
                            $this->image_lib->initialize($conf);
                            if(!$this->image_lib->resize()){
                                echo $this->image_lib->display_errors('','');
                            }
                        }
                        /* ********************F I N  para resize***************************** */
                        $confi['image_library'] = 'gd2';
                        $confi['source_image'] = './resources/images/asociado/'.$new_name.$extension;
                        $confi['new_image'] = './resources/images/asociado/'."thumb_".$new_name.$extension;
                        $confi['create_thumb'] = FALSE;
                        $confi['maintain_ratio'] = TRUE;
                        $confi['width'] = 50;
                        $confi['height'] = 50;

                        $this->image_lib->clear();
                        $this->image_lib->initialize($confi);
                        $this->image_lib->resize();

                        $foto = $new_name.$extension;
                        }else{
                            $img_data = $this->upload->data();
                            $extension = $img_data['file_ext'];
                            
                            $confi['image_library'] = 'gd2';
                            $confi['source_image'] = './resources/images/asociado/'.$new_name.$extension;
                            $confi['new_image'] = './resources/images/asociado/'."thumb_".$new_name.$extension;
                            $confi['create_thumb'] = FALSE;
                            $confi['maintain_ratio'] = TRUE;
                            $confi['width'] = 50;
                            $confi['height'] = 50;

                            $this->image_lib->clear();
                            $this->image_lib->initialize($confi);
                            $this->image_lib->resize();

                            
                            $foto = $new_name.$extension;
                        }
                    }
            /* *********************FIN imagen***************************** */
            //$estado_id = 1;
            $params = array(
                'asociado_id' => $detalleserv_id,
                //'estado_id' => $estado_id,
                'imagenasoc_titulo' => $foto,
                'imagenasoc_archivo' => $foto,
                'imagenasoc_descripcion' => $this->input->post('galeria_descripcion'),
            );
            
            $imagenasoc_id = $this->Imagen_asociado_model->add_imagen_asociado($params);
            //sleep(1);
            redirect('imagen_asociado/catalogoasoc/'.$detalleserv_id);
            
       // }
    }
    
    function eliminar($imagenprod_id)
    {
      //  if($this->acceso(69)){
        $imagen_producto = $this->Imagen_asociado_model->get_imagen_asociado($imagenprod_id);

        // check if the imagen_producto exists before trying to delete it
        if(isset($imagen_producto['imagenasoc_id']))
        {
            $imagen= $this->Imagen_asociado_model->get_imagen_asociado($imagenprod_id);
            $base_url = explode('/', base_url());
            //$directorio = FCPATH.'resources\images\clientes\\';
            $directorio = $_SERVER['DOCUMENT_ROOT'].'/'.$base_url[3].'/resources/images/asociado/';
            //$directorio = $_SERVER['DOCUMENT_ROOT'].'/ximpleman_web/resources/images/clientes/';
            $foto1 = $imagen['imagenasoc_archivo'];
            if(isset($foto1) && !empty($foto1)){
              if(file_exists($directorio.$foto1)){
                  unlink($directorio.$foto1);
                  $mimagenthumb = "thumb_".$foto1;
                  unlink($directorio.$mimagenthumb);
                }
            }
            $this->Imagen_asociado_model->delete_imagen($imagenprod_id);
            redirect('imagen_asociado/catalogoasoc/'.$imagen_producto['asociado_id']);
        }
        else
            show_error('The imagen_producto you are trying to delete does not exist.');
       // }
    }
    
    function galeriadetalle($asociado_id)
    {
      //  if($this->acceso(69)){
        $this->load->model('Asociado_model');
	$asociado = $this->Asociado_model->get_asociado($asociado_id);
        $data['id_asoc'] = $asociado_id;
        $data['asociado'] = $asociado['nombres_asoc']." ".$asociado['apellidos_asoc'];
        $data['all_imagen_asociado'] = $this->Imagen_asociado_model->get_all_imagen_mi_asociado($asociado_id);
        
        /*
        $this->load->model('Detalle_serv_model');
	$detalle_serv = $this->Detalle_serv_model->get_detalle_serv($detalleserv_id);
        $data['detalleserv_descripcion'] = $detalle_serv['detalleserv_descripcion'];
        $data['detalleserv_id'] = $detalleserv_id;
        $data['all_imagen_detalle_serv'] = $this->Imagen_producto_model->get_all_imagen_mi_det($detalleserv_id);
        */
        $data['_view'] = 'imagen_asociado/galeriadetalle';
        $this->load->view('layouts/main',$data);
       // }
    }
    
}
