<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Multum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Multum_model');
        $this->load->model('Estado_model');
        $this->load->model('Tipo_multum_model');
        $this->load->model('Me_model');
        $this->load->model('Gestion_model');
    } 

    /*
     * Listing of multa
     */
    function index()
    {
        $data['multa'] = $this->Multum_model->get_all_multa();
        
        $data['_view'] = 'multum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new multum
     */
    function add()
    {   
        $created_date = date("Y-m-d H:i:s");
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'motivo_multa' => $this->input->post('motivo_multa'),
				'detalle_multa' => $this->input->post('detalle_multa'),
				'monto_multa' => $this->input->post('monto_multa'),
				'fechahora_multa' => $created_date,
				'mes_multa' => $this->input->post('mes_multa'),
				'gestion_multa' => $this->input->post('gestion_multa'),
				'tipo_multa' => $this->input->post('tipo_multa'),
				'id_asoc' => $this->input->post('id_asoc'),
				'nombre_asoc' => $this->input->post('nombre_asoc'),
				'estado_multa' => 'ACTIVO',
				'id_usu' => 1,
				'exento_multa' => $this->input->post('exento_multa'),
				'ice_multa' => $this->input->post('ice_multa'),
            );
            
            $multum_id = $this->Multum_model->add_multum($params);
            redirect('multum/index');
        }
        else
        {            
            $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
            $data['all_estado'] = $this->Estado_model->get_all_estados();
            $data['all_mes'] = $this->Me_model->get_all_mes();
            $data['all_tipo'] = $this->Tipo_multum_model->get_all_tipo_multa();
            $data['_view'] = 'multum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a multum
     */
    function edit($id_multa)
    {   
        // check if the multum exists before trying to edit it
        $data['multum'] = $this->Multum_model->get_multum($id_multa);
        
        if(isset($data['multum']['id_multa']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'motivo_multa' => $this->input->post('motivo_multa'),
					'detalle_multa' => $this->input->post('detalle_multa'),
					'monto_multa' => $this->input->post('monto_multa'),
					'fechahora_multa' => $this->input->post('fechahora_multa'),
					'mes_multa' => $this->input->post('mes_multa'),
					'gestion_multa' => $this->input->post('gestion_multa'),
					'tipo_multa' => $this->input->post('tipo_multa'),
					'id_asoc' => $this->input->post('id_asoc'),
					'nombre_asoc' => $this->input->post('nombre_asoc'),
					'estado_multa' => $this->input->post('estado_multa'),
					'id_usu' => $this->input->post('id_usu'),
					'exento_multa' => $this->input->post('exento_multa'),
					'ice_multa' => $this->input->post('ice_multa'),
                );

                $this->Multum_model->update_multum($id_multa,$params);            
                redirect('multum/index');
            }
            else
            {
                $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
            $data['all_estado'] = $this->Estado_model->get_all_estados();
            $data['all_mes'] = $this->Me_model->get_all_mes();
            $data['all_tipo'] = $this->Tipo_multum_model->get_all_tipo_multa();
                $data['_view'] = 'multum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The multum you are trying to edit does not exist.');
    } 

    /*
     * Deleting multum
     */
    function remove($id_multa)
    {
        $multum = $this->Multum_model->get_multum($id_multa);

        // check if the multum exists before trying to delete it
        if(isset($multum['id_multa']))
        {
            $this->Multum_model->delete_multum($id_multa);
            redirect('multum/index');
        }
        else
            show_error('The multum you are trying to delete does not exist.');
    }
    
}
