<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Aporte_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get aporte by id_ap
     */
    function get_aporte($id_ap)
    {
        return $this->db->get_where('aporte',array('id_ap'=>$id_ap))->row_array();
    }
        
    /*
     * Get all aporte
     */
    function get_all_aporte()
    {
        $this->db->order_by('id_ap', 'desc');
        return $this->db->get('aporte')->result_array();
    }
        
    /*
     * function to add new aporte
     */
    function add_aporte($params)
    {
        $this->db->insert('aporte',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update aporte
     */
    function update_aporte($id_ap,$params)
    {
        $this->db->where('id_ap',$id_ap);
        return $this->db->update('aporte',$params);
    }
    
    /*
     * function to delete aporte
     */
    function delete_aporte($id_ap)
    {
        return $this->db->delete('aporte',array('id_ap'=>$id_ap));
    }
}
