<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado_aux_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asociado_aux by num
     */
    function get_asociado_aux($num)
    {
        return $this->db->get_where('asociado_aux',array('num'=>$num))->row_array();
    }
        
    /*
     * Get all asociado_aux
     */
    function get_all_asociado_aux()
    {
        $this->db->order_by('num', 'desc');
        return $this->db->get('asociado_aux')->result_array();
    }
        
    /*
     * function to add new asociado_aux
     */
    function add_asociado_aux($params)
    {
        $this->db->insert('asociado_aux',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asociado_aux
     */
    function update_asociado_aux($num,$params)
    {
        $this->db->where('num',$num);
        return $this->db->update('asociado_aux',$params);
    }
    
    /*
     * function to delete asociado_aux
     */
    function delete_asociado_aux($num)
    {
        return $this->db->delete('asociado_aux',array('num'=>$num));
    }
}
