<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asociado by id_asoc
     */
    function get_asociado($id_asoc)
    {
        return $this->db->get_where('asociado',array('id_asoc'=>$id_asoc))->row_array();
    }
        
    /*
     * Get all asociado
     */
    function get_all_asociado()
    {
        $this->db->order_by('id_asoc', 'desc');
        return $this->db->get('asociado')->result_array();
    }
        
    /*
     * function to add new asociado
     */
    function add_asociado($params)
    {
        $this->db->insert('asociado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asociado
     */
    function update_asociado($id_asoc,$params)
    {
        $this->db->where('id_asoc',$id_asoc);
        return $this->db->update('asociado',$params);
    }
    
    /*
     * function to delete asociado
     */
    function delete_asociado($id_asoc)
    {
        return $this->db->delete('asociado',array('id_asoc'=>$id_asoc));
    }
    function get_busqueda_asociado($parametro)
    {
        $sql = "select
                a.id_asoc, a.nombres_asoc, a.apellidos_asoc, a.codigo_asoc, a.razon_asoc, a.ci_asoc,
                a.nit_asoc, a.direccion_asoc, a.medidor_asoc, ifnull(t1.este_lec, 0) as ultima_lectura
                from asociado a
                LEFT JOIN
                  (SELECT l.actual_lec as este_lec, l.id_asoc as esteasoc_id
                    FROM lectura l group by l.id_asoc desc ) as t1 on t1.esteasoc_id = a.id_asoc
                where
                a.nombres_asoc like '%".$parametro."%' or a.apellidos_asoc like '%".$parametro."%'
                or a.codigo_asoc = '".$parametro."' or a.razon_asoc like '%".$parametro."%'
                or a.ci_asoc like '%".$parametro."%' or a.nit_asoc like '%".$parametro."%'";

        $asociado = $this->db->query($sql)->result_array();
        return $asociado;

    }    
    
}
