<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asociado by id_asoc
     */
    function get_asociado($id_asoc)
    {
        return $this->db->get_where('asociado',array('id_asoc'=>$id_asoc))->row_array();
    }

    function get_pendientes($id_asoc)
    {
        $pendientes = $this->db->query("
             SELECT
                f.* , l.id_asoc
            FROM
                factura f, lectura l 
            
            
            WHERE f.id_lec=l.id_lec
            and f.estado_fact='PENDIENTE'
            and l.id_asoc=".$id_asoc."

        ")->result_array();

        return $pendientes;
    }
    function get_canceladas($id_asoc)
    {
        $cancelados = $this->db->query("
            SELECT
                f.* , l.id_asoc
            FROM
                factura f, lectura l 
            
            
            WHERE f.id_lec=l.id_lec
            and f.estado_fact='CANCELADA'
            and l.id_asoc=".$id_asoc."

        ")->result_array();

        return $cancelados;
    }
        
    /*
     * Get all asociado
     */
    function get_all_asociado()
    {
        $this->db->order_by('id_asoc', 'desc');
        return $this->db->get('asociado')->result_array();
    }
        
    /*
     * function to add new asociado
     */
    function add_asociado($params)
    {
        $this->db->insert('asociado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asociado
     */
    function update_asociado($id_asoc,$params)
    {
        $this->db->where('id_asoc',$id_asoc);
        return $this->db->update('asociado',$params);
    }
    
    /*
     * function to delete asociado
     */
    function delete_asociado($id_asoc)
    {
        return $this->db->delete('asociado',array('id_asoc'=>$id_asoc));
    }
}
