<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bitacora_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bitacora by id_bit
     */
    function get_bitacora($id_bit)
    {
        return $this->db->get_where('bitacora',array('id_bit'=>$id_bit))->row_array();
    }
        
    /*
     * Get all bitacora
     */
    function get_all_bitacora()
    {
        $this->db->order_by('id_bit', 'desc');
        return $this->db->get('bitacora')->result_array();
    }
        
    /*
     * function to add new bitacora
     */
    function add_bitacora($params)
    {
        $this->db->insert('bitacora',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bitacora
     */
    function update_bitacora($id_bit,$params)
    {
        $this->db->where('id_bit',$id_bit);
        return $this->db->update('bitacora',$params);
    }
    
    /*
     * function to delete bitacora
     */
    function delete_bitacora($id_bit)
    {
        return $this->db->delete('bitacora',array('id_bit'=>$id_bit));
    }
}
