<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categorium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categorium by id_cating
     */
    function get_categorium($id_cating)
    {
        return $this->db->get_where('categoria',array('id_cating'=>$id_cating))->row_array();
    }
        
    /*
     * Get all categoria
     */
    function get_all_categoria()
    {
        $this->db->order_by('id_cating', 'desc');
        return $this->db->get('categoria')->result_array();
    }
        
    /*
     * function to add new categorium
     */
    function add_categorium($params)
    {
        $this->db->insert('categoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categorium
     */
    function update_categorium($id_cating,$params)
    {
        $this->db->where('id_cating',$id_cating);
        return $this->db->update('categoria',$params);
    }
    
    /*
     * function to delete categorium
     */
    function delete_categorium($id_cating)
    {
        return $this->db->delete('categoria',array('id_cating'=>$id_cating));
    }
}
