<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Detalle_factura_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detalle_factura by id_detfact
     */
    function get_detalle_factura($id_detfact)
    {
        return $this->db->get_where('detalle_factura',array('id_detfact'=>$id_detfact))->row_array();
    }
        
    /*
     * Get all detalle_factura
     */
    function get_all_detalle_factura()
    {
        $this->db->order_by('id_detfact', 'desc');
        return $this->db->get('detalle_factura')->result_array();
    }
        
    /*
     * function to add new detalle_factura
     */
    function add_detalle_factura($params)
    {
        $this->db->insert('detalle_factura',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update detalle_factura
     */
    function update_detalle_factura($id_detfact,$params)
    {
        $this->db->where('id_detfact',$id_detfact);
        return $this->db->update('detalle_factura',$params);
    }
    
    /*
     * function to delete detalle_factura
     */
    function delete_detalle_factura($id_detfact)
    {
        return $this->db->delete('detalle_factura',array('id_detfact'=>$id_detfact));
    }
}
