<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Direccion_orden_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get direccion_orden by id_dir
     */
    function get_direccion_orden($id_dir)
    {
        return $this->db->get_where('direccion_orden',array('id_dir'=>$id_dir))->row_array();
    }
        
    /*
     * Get all direccion_orden
     */
    function get_all_direccion_orden()
    {
        $this->db->order_by('id_dir', 'desc');
        return $this->db->get('direccion_orden')->result_array();
    }
        
    /*
     * function to add new direccion_orden
     */
    function add_direccion_orden($params)
    {
        $this->db->insert('direccion_orden',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update direccion_orden
     */
    function update_direccion_orden($id_dir,$params)
    {
        $this->db->where('id_dir',$id_dir);
        return $this->db->update('direccion_orden',$params);
    }
    
    /*
     * function to delete direccion_orden
     */
    function delete_direccion_orden($id_dir)
    {
        return $this->db->delete('direccion_orden',array('id_dir'=>$id_dir));
    }
}
