<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empresa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get empresa by id_emp
     */
    function get_empresa($id_emp)
    {
        return $this->db->get_where('empresa',array('id_emp'=>$id_emp))->row_array();
    }
        
    /*
     * Get all empresa
     */
    function get_all_empresa()
    {
        $this->db->order_by('id_emp', 'desc');
        return $this->db->get('empresa')->result_array();
    }
        
    /*
     * function to add new empresa
     */
    function add_empresa($params)
    {
        $this->db->insert('empresa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update empresa
     */
    function update_empresa($id_emp,$params)
    {
        $this->db->where('id_emp',$id_emp);
        return $this->db->update('empresa',$params);
    }
    
    /*
     * function to delete empresa
     */
    function delete_empresa($id_emp)
    {
        return $this->db->delete('empresa',array('id_emp'=>$id_emp));
    }
}
