<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by estado
     */
    function get_estado($estado)
    {
        return $this->db->get_where('estados',array('estado'=>$estado))->row_array();
    }
        
    /*
     * Get all estados
     */
    function get_all_estados()
    {
        $this->db->order_by('estado', 'desc');
        return $this->db->get('estados')->result_array();
    }
        
    /*
     * function to add new estado
     */
    function add_estado($params)
    {
        $this->db->insert('estados',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estado
     */
    function update_estado($estado,$params)
    {
        $this->db->where('estado',$estado);
        return $this->db->update('estados',$params);
    }
    
    /*
     * function to delete estado
     */
    function delete_estado($estado)
    {
        return $this->db->delete('estados',array('estado'=>$estado));
    }
}
