<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Expedido_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get expedido by ciudad
     */
    function get_expedido($ciudad)
    {
        return $this->db->get_where('expedido',array('ciudad'=>$ciudad))->row_array();
    }
        
    /*
     * Get all expedido
     */
    function get_all_expedido()
    {
        $this->db->order_by('ciudad', 'desc');
        return $this->db->get('expedido')->result_array();
    }
        
    /*
     * function to add new expedido
     */
    function add_expedido($params)
    {
        $this->db->insert('expedido',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update expedido
     */
    function update_expedido($ciudad,$params)
    {
        $this->db->where('ciudad',$ciudad);
        return $this->db->update('expedido',$params);
    }
    
    /*
     * function to delete expedido
     */
    function delete_expedido($ciudad)
    {
        return $this->db->delete('expedido',array('ciudad'=>$ciudad));
    }
}
