<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Factura_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get factura by id_fact
     */
    function get_factura($id_fact)
    {
        return $this->db->get_where('factura',array('id_fact'=>$id_fact))->row_array();
    }
        
    /*
     * Get all factura
     */
    function get_all_factura()
    {
        $this->db->order_by('id_fact', 'desc');
        return $this->db->get('factura')->result_array();
    }
        
    /*
     * function to add new factura
     */
    function add_factura($params)
    {
        $this->db->insert('factura',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update factura
     */
    function update_factura($id_fact,$params)
    {
        $this->db->where('id_fact',$id_fact);
        return $this->db->update('factura',$params);
    }
    
    /*
     * function to delete factura
     */
    function delete_factura($id_fact)
    {
        return $this->db->delete('factura',array('id_fact'=>$id_fact));
    }
}
