<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imagen_asociado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function get_all_imagen_mi_asociado($id_asoc)
    {
        $imagen = $this->db->query("
            SELECT
                i.*
            FROM
                imagen_asociado i, asociado a
            WHERE
                i.asociado_id = a.id_asoc
                and i.asociado_id = '$id_asoc'
            ORDER BY `imagenasoc_id` DESC

        ")->result_array();

        return $imagen;
    }
    
    function add_imagen_asociado($params)
    {
        $this->db->insert('imagen_asociado',$params);
        return $this->db->insert_id();
    }
    function get_imagen_asociado($imagenprod_id)
    {
        $imagen = $this->db->query("
            SELECT
                *

            FROM
                `imagen_asociado`

            WHERE
                `imagenasoc_id` = ?
        ",array($imagenprod_id))->row_array();

        return $imagen;
    }
    function delete_imagen($imagenprod_id)
    {
        return $this->db->delete('imagen_asociado',array('imagenasoc_id'=>$imagenprod_id));
    }
    
}
