<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ingreso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ingreso by id_ing
     */
    function get_ingreso($id_ing)
    {
        return $this->db->get_where('ingreso',array('id_ing'=>$id_ing))->row_array();
    }
        
    /*
     * Get all ingreso
     */
    function get_all_ingreso()
    {
        $this->db->order_by('id_ing', 'desc');
        return $this->db->get('ingreso')->result_array();
    }
        
    /*
     * function to add new ingreso
     */
    function add_ingreso($params)
    {
        $this->db->insert('ingreso',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ingreso
     */
    function update_ingreso($id_ing,$params)
    {
        $this->db->where('id_ing',$id_ing);
        return $this->db->update('ingreso',$params);
    }
    
    /*
     * function to delete ingreso
     */
    function delete_ingreso($id_ing)
    {
        return $this->db->delete('ingreso',array('id_ing'=>$id_ing));
    }
}
