<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Me_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get me by id_mes
     */
    function get_me($id_mes)
    {
        return $this->db->get_where('mes',array('id_mes'=>$id_mes))->row_array();
    }
        
    /*
     * Get all mes
     */
    function get_all_mes()
    {
        $this->db->order_by('id_mes', 'desc');
        return $this->db->get('mes')->result_array();
    }
        
    /*
     * function to add new me
     */
    function add_me($params)
    {
        $this->db->insert('mes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update me
     */
    function update_me($id_mes,$params)
    {
        $this->db->where('id_mes',$id_mes);
        return $this->db->update('mes',$params);
    }
    
    /*
     * function to delete me
     */
    function delete_me($id_mes)
    {
        return $this->db->delete('mes',array('id_mes'=>$id_mes));
    }
}
