<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Medidor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get medidor by id_med
     */
    function get_medidor($id_med)
    {
        return $this->db->get_where('medidor',array('id_med'=>$id_med))->row_array();
    }
        
    /*
     * Get all medidor
     */
    function get_all_medidor()
    {
        $this->db->order_by('id_med', 'desc');
        return $this->db->get('medidor')->result_array();
    }
        
    /*
     * function to add new medidor
     */
    function add_medidor($params)
    {
        $this->db->insert('medidor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update medidor
     */
    function update_medidor($id_med,$params)
    {
        $this->db->where('id_med',$id_med);
        return $this->db->update('medidor',$params);
    }
    
    /*
     * function to delete medidor
     */
    function delete_medidor($id_med)
    {
        return $this->db->delete('medidor',array('id_med'=>$id_med));
    }
}
