<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parametro_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get parametro by id_param
     */
    function get_parametro($id_param)
    {
        return $this->db->get_where('parametros',array('id_param'=>$id_param))->row_array();
    }
        
    /*
     * Get all parametros
     */
    function get_all_parametros()
    {
        $this->db->order_by('id_param', 'desc');
        return $this->db->get('parametros')->result_array();
    }
        
    /*
     * function to add new parametro
     */
    function add_parametro($params)
    {
        $this->db->insert('parametros',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parametro
     */
    function update_parametro($id_param,$params)
    {
        $this->db->where('id_param',$id_param);
        return $this->db->update('parametros',$params);
    }
    
    /*
     * function to delete parametro
     */
    function delete_parametro($id_param)
    {
        return $this->db->delete('parametros',array('id_param'=>$id_param));
    }
}
