<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarifa_parametrizable_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tarifa_parametrizable by id_tarifa
     */
    function get_tarifa_parametrizable($id_tarifa)
    {
        return $this->db->get_where('tarifa_parametrizable',array('id_tarifa'=>$id_tarifa))->row_array();
    }
        
    /*
     * Get all tarifa_parametrizable
     */
    function get_all_tarifa_parametrizable()
    {
        $this->db->order_by('id_tarifa', 'desc');
        return $this->db->get('tarifa_parametrizable')->result_array();
    }
        
    /*
     * function to add new tarifa_parametrizable
     */
    function add_tarifa_parametrizable($params)
    {
        $this->db->insert('tarifa_parametrizable',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tarifa_parametrizable
     */
    function update_tarifa_parametrizable($id_tarifa,$params)
    {
        $this->db->where('id_tarifa',$id_tarifa);
        return $this->db->update('tarifa_parametrizable',$params);
    }
    
    /*
     * function to delete tarifa_parametrizable
     */
    function delete_tarifa_parametrizable($id_tarifa)
    {
        return $this->db->delete('tarifa_parametrizable',array('id_tarifa'=>$id_tarifa));
    }
}
