<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarifa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tarifa by id_tarifa
     */
    function get_tarifa($id_tarifa)
    {
        return $this->db->get_where('tarifa',array('id_tarifa'=>$id_tarifa))->row_array();
    }
        
    /*
     * Get all tarifa
     */
    function get_all_tarifa()
    {
        $this->db->order_by('id_tarifa', 'desc');
        return $this->db->get('tarifa')->result_array();
    }
        
    /*
     * function to add new tarifa
     */
    function add_tarifa($params)
    {
        $this->db->insert('tarifa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tarifa
     */
    function update_tarifa($id_tarifa,$params)
    {
        $this->db->where('id_tarifa',$id_tarifa);
        return $this->db->update('tarifa',$params);
    }
    
    /*
     * function to delete tarifa
     */
    function delete_tarifa($id_tarifa)
    {
        return $this->db->delete('tarifa',array('id_tarifa'=>$id_tarifa));
    }
    /* obtener tarifa */
    function get_estatarifa($consumo_lec, $tipo_asoc)
    {
        $sql = "select t.costo_agua, t.costo_alcant, t.id_tarifa
                from tarifa t
                where
                t.desde >= $consumo_lec
                and t.hasta <= $consumo_lec
                and t.tipo = '".$tipo_asoc."'";

        $asociado = $this->db->query($sql)->row_array();
        return $asociado;
    }    
}
