<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_multum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_multum by tipo
     */
    function get_tipo_multum($tipo)
    {
        return $this->db->get_where('tipo_multa',array('tipo'=>$tipo))->row_array();
    }
        
    /*
     * Get all tipo_multa
     */
    function get_all_tipo_multa()
    {
        $this->db->order_by('tipo', 'desc');
        return $this->db->get('tipo_multa')->result_array();
    }
        
    /*
     * function to add new tipo_multum
     */
    function add_tipo_multum($params)
    {
        $this->db->insert('tipo_multa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_multum
     */
    function update_tipo_multum($tipo,$params)
    {
        $this->db->where('tipo',$tipo);
        return $this->db->update('tipo_multa',$params);
    }
    
    /*
     * function to delete tipo_multum
     */
    function delete_tipo_multum($tipo)
    {
        return $this->db->delete('tipo_multa',array('tipo'=>$tipo));
    }
}
