<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_asociado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_asociado by tipo_asoc
     */
    function get_tipo_asociado($tipo_asoc)
    {
        return $this->db->get_where('tipo_asociado',array('tipo_asoc'=>$tipo_asoc))->row_array();
    }
        
    /*
     * Get all tipo_asociado
     */
    function get_all_tipo_asociado()
    {
        $this->db->order_by('tipo_asoc', 'desc');
        return $this->db->get('tipo_asociado')->result_array();
    }
        
    /*
     * function to add new tipo_asociado
     */
    function add_tipo_asociado($params)
    {
        $this->db->insert('tipo_asociado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_asociado
     */
    function update_tipo_asociado($tipo_asoc,$params)
    {
        $this->db->where('tipo_asoc',$tipo_asoc);
        return $this->db->update('tipo_asociado',$params);
    }
    
    /*
     * function to delete tipo_asociado
     */
    function delete_tipo_asociado($tipo_asoc)
    {
        return $this->db->delete('tipo_asociado',array('tipo_asoc'=>$tipo_asoc));
    }
}
